-- Run after add_trip_login.sql. This keeps anonymous writes behind RPCs,
-- while reflections use the existing trip session token.

create table if not exists public.trip_confessions (
  id bigint generated by default as identity (start with 10045) primary key,
  author_token uuid not null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint trip_confessions_body_len check (
    char_length(btrim(body)) between 1 and 800
  )
);

create index if not exists trip_confessions_created_at_idx
  on public.trip_confessions (created_at desc, id desc);

create index if not exists trip_confessions_author_created_at_idx
  on public.trip_confessions (author_token, created_at desc);

alter table public.trip_confessions enable row level security;
revoke all on public.trip_confessions from anon, authenticated;

create or replace function public.trip_confession_submit(
  p_author_token uuid,
  p_body text
)
returns table (
  id bigint,
  body text,
  "createdAt" timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_body text := btrim(coalesce(p_body, ''));
begin
  if char_length(v_body) not between 1 and 800 then
    raise exception 'Confession cần từ 1 đến 800 ký tự.';
  end if;

  -- A browser-local anonymous token cannot stop determined abuse, but it
  -- prevents accidental repeat submissions and ordinary client-side spam.
  perform pg_advisory_xact_lock(hashtext(p_author_token::text));

  if exists (
    select 1
    from public.trip_confessions c
    where c.author_token = p_author_token
      and c.created_at > now() - interval '30 seconds'
  ) then
    raise exception 'Bạn vừa gửi rồi, chờ 30 giây nhé.';
  end if;

  if (
    select count(*)
    from public.trip_confessions c
    where c.author_token = p_author_token
      and c.created_at >= now() - interval '24 hours'
  ) >= 15 then
    raise exception 'Bạn đã gửi đủ 15 confession trong hôm nay.';
  end if;

  return query
  insert into public.trip_confessions (author_token, body)
  values (p_author_token, v_body)
  returning trip_confessions.id, trip_confessions.body, trip_confessions.created_at;
end;
$$;

create or replace function public.trip_confession_list()
returns table (
  id bigint,
  body text,
  "createdAt" timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select c.id, c.body, c.created_at as "createdAt"
  from public.trip_confessions c
  order by c.created_at desc, c.id desc
  limit 100;
$$;

create table if not exists public.trip_reflections (
  username text primary key references public.trip_members(username) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_reflections_body_len check (char_length(btrim(body)) >= 1)
);

create index if not exists trip_reflections_updated_at_idx
  on public.trip_reflections (updated_at desc, username);

alter table public.trip_reflections enable row level security;
revoke all on public.trip_reflections from anon, authenticated;

create or replace function public.trip_reflection_member_from_token(p_session_token text)
returns public.trip_members
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select m
  from public.trip_sessions s
  join public.trip_members m on m.username = s.username
  where s.session_hash = extensions.digest(coalesce(p_session_token, ''), 'sha256')
    and s.expires_at > now()
  limit 1;
$$;

create or replace function public.trip_reflections_get(p_session_token text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_member public.trip_members%rowtype;
  -- Keep this server-side rule aligned with TRIP_DATA.reflectionOpensAt.
  v_opens_at constant timestamptz := timestamptz '2026-07-19 00:00:00+07';
  v_is_open boolean := now() >= v_opens_at;
begin
  select * into v_member
  from public.trip_reflection_member_from_token(p_session_token);

  return jsonb_build_object(
    'open', v_is_open,
    'opensAt', v_opens_at,
    'authenticated', v_member.username is not null,
    'viewer', case when v_member.username is null then null else jsonb_build_object(
      'username', v_member.username,
      'displayName', v_member.display_name
    ) end,
    'reflection', case when v_member.username is null or not v_is_open then null else (
      select jsonb_build_object('body', r.body, 'updatedAt', r.updated_at)
      from public.trip_reflections r
      where r.username = v_member.username
    ) end,
    'reflections', case when not v_is_open then '[]'::jsonb else coalesce((
      select jsonb_agg(jsonb_build_object(
        'username', r.username,
        'displayName', m.display_name,
        'body', r.body,
        'updatedAt', r.updated_at
      ) order by r.updated_at desc, r.username)
      from public.trip_reflections r
      join public.trip_members m on m.username = r.username
    ), '[]'::jsonb) end
  );
end;
$$;

create or replace function public.trip_reflections_save(
  p_session_token text,
  p_body text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_member public.trip_members%rowtype;
  v_body text := btrim(coalesce(p_body, ''));
  -- The database is the authority for the opening time, not the browser.
  v_opens_at constant timestamptz := timestamptz '2026-07-19 00:00:00+07';
begin
  if now() < v_opens_at then
    raise exception 'Cảm nhận sẽ mở từ 00:00 Chủ Nhật 19/07 (UTC+7).';
  end if;

  select * into v_member
  from public.trip_reflection_member_from_token(p_session_token);

  if v_member.username is null then
    raise exception 'Bạn cần đăng nhập để viết cảm nhận.';
  end if;

  if char_length(v_body) < 1 then
    raise exception 'Cảm nhận không được để trống.';
  end if;

  insert into public.trip_reflections (username, body, updated_at)
  values (v_member.username, v_body, now())
  on conflict (username) do update
  set body = excluded.body,
      updated_at = excluded.updated_at;

  return public.trip_reflections_get(p_session_token);
end;
$$;

revoke all on function public.trip_confession_submit(uuid, text) from public;
revoke all on function public.trip_confession_list() from public;
revoke all on function public.trip_reflection_member_from_token(text) from public;
revoke all on function public.trip_reflections_get(text) from public;
revoke all on function public.trip_reflections_save(text, text) from public;

grant execute on function public.trip_confession_submit(uuid, text) to anon;
grant execute on function public.trip_confession_list() to anon;
grant execute on function public.trip_reflections_get(text) to anon;
grant execute on function public.trip_reflections_save(text, text) to anon;
